#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>          /* See NOTES */
#include <sys/socket.h>
#include <netinet/in.h>
#include <errno.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netdb.h>
#include "template.h"


int parse_str(const char *str, struct numbers *n)
{
	int ret;
	unsigned short sa, sc;
	ret = sscanf(str, "%hu %u %hu %hu %u", &sa, &n->b, &sc, &n->d, &n->e);
	n->a = sa;
	n->c = sc;
	return ret;
}

void output_str(char *str, size_t len, const struct numbers *n)
{
	snprintf(str, len, "%u %u %u %u %u", n->a, n->b, n->c, n->d, n->e);
}
int main(int argc, char *argv[])
{

  int sock;
  struct sockaddr_in server;
  char s_Id[]="464468\n";
  char task[]="1.2-binary\n";
	char buffer[200];
	int len;
  struct numbers receive;
	int receiveval;

  //socket created here
  if ((sock=socket(AF_INET, SOCK_STREAM,0))==-1){
    perror("socket: ");
    exit(-1);
  }
  memset(&server, 0, sizeof(server));
  server.sin_family=AF_INET;
  server.sin_port=htons(5000);
  server.sin_addr.s_addr = inet_addr("195.148.124.76");
  bzero(&server.sin_zero,8);
  int len2 =sizeof(server);

    //connecting to server
    if (connect(sock,(struct sockaddr *)&server,len2) == -1) {
           perror("connection error occur");
           exit(-1) ;
       }



      //send Id to server                               //send Task name
       if(((send(sock, s_Id, strlen(s_Id), 0))>0) && ((send(sock, task, strlen(task), 0))>0)){


       //read the one line string that the server sent

			 if((len=recv(sock, buffer, 1024, 0))>0){
       buffer[len]='\0';
			 printf("------------step reading server message-------------\n");
			 printf(" message= %s bytes= %d \n",buffer,len);
			 printf("------------step calling the  parse_str()-------------\n");
			 receiveval=parse_str(buffer,&receive);
			 printf("value sent : %d\n",receiveval );
			 printf("------------step sending the numbers to server that was generated by the parse_str()-------------\n");
          //uint8_t a=htons((uint8_t)receive.a);
					int b=htonl(receive.b);
					//int c=htons(receive.c);
					int d=htons(receive.d);
					int e=htonl(receive.e);
					//printf("%d - %d",receive.a, a);
					if((send(sock,&receive.a,sizeof(receive.a),0))!=sizeof(receive.a)){
						exit(-1);

					}
					if((send(sock,&b,sizeof(b),0))!=sizeof(b)){
						exit(-1);
					}
					if((send(sock,&receive.c,sizeof(receive.c),0))!=sizeof(receive.c)){
						exit(-1);
					}
					if((send(sock,&d,sizeof(receive.d),0))!=sizeof(receive.d)){
						exit(-1);
					}
					if((send(sock,&e,sizeof(e),0))!=sizeof(e)){
						exit(-1);
					}
			 printf("------------reading binary from server-------------\n");
					int byteread=12; int recvbyte; char * p=buffer;
					while(byteread>0){
					if((recvbyte=recv(sock, p, byteread, 0))<0){
						exit(-1);
					}
					byteread-=recvbyte;
					p+=recvbyte;

				}
				receive.a=buffer[0];
				printf("%d\n",receive.a);
				receive.b=ntohl(*(uint32_t*)(buffer+1));
				printf("%d\n",receive.b);
				receive.c=buffer[5];
				receive.d=ntohs(*(uint32_t*)(buffer+6));
				printf("%d\n",receive.d);
				receive.e=ntohl(*(uint32_t*)(buffer+8));
				output_str(buffer,200,&receive);
				printf("%s",buffer);
				if((send(sock, buffer, 1024, 0))<0){
					return -1;
				}
				if((recv(sock, buffer, 1024, 0))<0){
 				 exit(-1);
 			 }
			 printf("%s\n",buffer);


		 }

		 }


       close(sock);



  return 0;



}
